Visitor can sign up
CraftAcademy/slowfood-jan2019-team1 pull request #4
Opened 2019-02-21 16:48 UTC by amandagibson

# Visitor can sign up feature:

[Visitor can sign up](https://www.pivotaltracker.com/n/projects/2284621/stories/163901513)

# User Story

As a user,
In order to be able to finalize an order
I would like to be able to register an account

# Description of PR

This PR includes the addition and configuration of devise gem which allows visitors to sign up with all feature tests going green. It also includes the addition of a factory bot.
![screenshot 2019-02-21 at 15 51 05](https://user-images.githubusercontent.com/43479149/53186186-cc7aa380-3600-11e9-848c-2ac0b96906e8.png)

2019-02-21 17:58 UTC, nevroje commented
Did we get the sad path?

2019-02-22 08:54 UTC, Joberg95 approved these changes

2019-02-22 08:58 UTC, yanqiuzhang approved these changes

2019-02-22 09:24 UTC, boamatule reviewed
Perfect

2019-02-22 09:29 UTC, boamatule approved these changes

2019-02-22 09:34 UTC, boamatule approved these changes

2019-02-22 09:45 UTC, faraznaeem requested changes

2019-02-22 09:45 UTC, faraznaeem commented on features/visitor_can_sign_up.feature
> +		Given I visit the landing page
indention is off in this file, please follow your own standard in the different files.

2019-02-22 09:45 UTC, faraznaeem commented on config/routes.rb
> +  root controller: :welcome, action: :index
route is set to the welcome controller

2019-02-22 09:45 UTC, faraznaeem commented on app/views/welcome/index.html.haml
> +%p Find me in app/views/welcome/index.html.haml
No need for this file

2019-02-22 09:45 UTC, faraznaeem commented on app/controllers/welcome_controller.rb
> +end
Remove controller

2019-02-22 09:46 UTC, nevroje commented on config/routes.rb
> +  root controller: :welcome, action: :index
Should be like this ``` Rails.application.routes.draw do
	root controller: :products, action: :index
end ```

2019-02-22 10:01 UTC, oliverochman approved these changes

2019-02-22 10:02 UTC, merged